# Use my custom theme
include citruszest-theme.conf

# Fix issue with 'delete' adding spaces in SSH
term    xterm-256color

# Allow running kitty config commands from the command line
allow_remote_control yes

# Use left Option key as Alt
macos_option_as_alt left
