bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded config!"

# Reset prefix
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Allow mouse usage
set -g mouse on

# Moving between windows
bind-key -n C-Left previous-window 
bind-key -n C-Right next-window
bind-key -n C-h previous-window
bind-key -n C-l next-window

# Fix escape delay in Neovim
set-option -g escape-time 10
